name: Telekinesis
version: '1.5.2'
main: net.itzrenzo.telekinesis.Telekinesis
api-version: '1.17'
authors: [ ItzRenzo ]
soft-depend: [WorldGuard, MythicMobs]
commands:
  telekinesis:
    description: Toggle Telekinesis, reload the plugin, or manage blacklist
    usage: /<command> <on|off|reload|blacklist>
permissions:
  telekinesis.use:
    description: Allows the use of Telekinesis
    default: op
  telekinesis.reload:
    description: Allows reloading the Telekinesis plugin
    default: op
  telekinesis.blacklist:
    description: Allows managing personal blacklist
    default: op
  telekinesis.blacklist.list:
    description: Allows listing personal blacklisted items
    default: op